#-----------------------------------------BASICS-------------------------------------
urls                = [''] # urls (array) to monitor urls
wait_time           =  5 #customizable time to wait to check for changes IE every 20 secs
headers             = {'User-Agent': "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"}


#------------------------------------GMAIL SECTION----------------------------------

notify              = True #True to notify via email on change False

user                = '' #emailuser@gmail.com
pwd                 = ''  #app password generated by google IE "djfj rubi sifu sofi"
recipient           = '' #recievingemail@gmail.com


# ----------------------------------TWITTER SECTION------------------------------------

tweet               = False #True to tweet on change, False not to

consumer_key        = ''
consumer_secret     = ''
access_token        = ''
access_token_secret = ''


 #---------------------------------SMS SECTION------------------------------------------
#https://www.twilio.com/console/account/settings

text                 = True #True to send text, false to not

accountSID          = ''
authToken           = ''
myNumber            = '' #number to send text messages to
twilioNumber        = '' #twillio phone number

